ALTER TABLE "InvoicePayment"
ADD COLUMN IF NOT EXISTS "refundAmount" DECIMAL(15,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "refundedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "voidedAt" TIMESTAMP(3);
