// src/components/chat/data.ts

import { User, Conversation, Message } from "./types";

export const currentUser: User = {
  id: "current",
  name: "John Doe",
  email: "john@yoursoft.ca",
  status: "online",
};

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Wilson",
    avatar: "",
    email: "sarah@client.com",
    phone: "+1 (555) 123-4567",
    company: "Tech Solutions Inc.",
    role: "Project Manager",
    location: "New York, USA",
    status: "online",
  },
  {
    id: "2",
    name: "Michael Chen",
    avatar: "",
    email: "michael@startup.io",
    phone: "+1 (555) 234-5678",
    company: "StartupXYZ",
    role: "CEO",
    location: "San Francisco, USA",
    status: "away",
    lastSeen: new Date(Date.now() - 15 * 60000),
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    avatar: "",
    email: "emily@design.co",
    phone: "+1 (555) 345-6789",
    company: "Creative Design Co.",
    role: "Lead Designer",
    location: "Los Angeles, USA",
    status: "offline",
    lastSeen: new Date(Date.now() - 2 * 3600000),
  },
  {
    id: "4",
    name: "David Kim",
    avatar: "",
    email: "david@enterprise.com",
    phone: "+1 (555) 456-7890",
    company: "Enterprise Corp",
    role: "CTO",
    location: "Seattle, USA",
    status: "busy",
  },
  {
    id: "5",
    name: "Lisa Thompson",
    avatar: "",
    email: "lisa@marketing.io",
    phone: "+1 (555) 567-8901",
    company: "Marketing Pro",
    role: "Marketing Director",
    location: "Chicago, USA",
    status: "online",
  },
  {
    id: "6",
    name: "James Brown",
    avatar: "",
    email: "james@sales.com",
    phone: "+1 (555) 678-9012",
    company: "Sales Force",
    role: "Sales Manager",
    location: "Boston, USA",
    status: "online",
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv1",
    type: "direct",
    participants: [currentUser, mockUsers[0]],
    lastMessage: {
      id: "m1",
      senderId: "1",
      content: "Sure, I'll send over the project files by EOD!",
      timestamp: new Date(Date.now() - 5 * 60000),
      status: "read",
    },
    unreadCount: 0,
    isPinned: true,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 7 * 24 * 3600000),
    updatedAt: new Date(Date.now() - 5 * 60000),
  },
  {
    id: "conv2",
    type: "direct",
    participants: [currentUser, mockUsers[1]],
    lastMessage: {
      id: "m2",
      senderId: "2",
      content: "The meeting has been rescheduled to 3 PM tomorrow.",
      timestamp: new Date(Date.now() - 30 * 60000),
      status: "delivered",
    },
    unreadCount: 2,
    isPinned: true,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 14 * 24 * 3600000),
    updatedAt: new Date(Date.now() - 30 * 60000),
  },
  {
    id: "conv3",
    type: "group",
    name: "Project Alpha Team",
    participants: [currentUser, mockUsers[0], mockUsers[2], mockUsers[3]],
    lastMessage: {
      id: "m3",
      senderId: "3",
      content: "I've uploaded the new designs to the shared folder.",
      timestamp: new Date(Date.now() - 2 * 3600000),
      status: "read",
      attachments: [{ id: "a1", type: "file", name: "designs_v2.zip", url: "#", size: "24.5 MB" }],
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 30 * 24 * 3600000),
    updatedAt: new Date(Date.now() - 2 * 3600000),
  },
  {
    id: "conv4",
    type: "direct",
    participants: [currentUser, mockUsers[3]],
    lastMessage: {
      id: "m4",
      senderId: "current",
      content: "Thanks for the update on the server migration!",
      timestamp: new Date(Date.now() - 5 * 3600000),
      status: "read",
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: true,
    isArchived: false,
    createdAt: new Date(Date.now() - 60 * 24 * 3600000),
    updatedAt: new Date(Date.now() - 5 * 3600000),
  },
  {
    id: "conv5",
    type: "direct",
    participants: [currentUser, mockUsers[4]],
    lastMessage: {
      id: "m5",
      senderId: "5",
      content: "Here's the marketing report you requested 📊",
      timestamp: new Date(Date.now() - 24 * 3600000),
      status: "read",
      attachments: [{ id: "a2", type: "file", name: "Q4_Marketing_Report.pdf", url: "#", size: "2.3 MB" }],
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 45 * 24 * 3600000),
    updatedAt: new Date(Date.now() - 24 * 3600000),
  },
  {
    id: "conv6",
    type: "group",
    name: "Sales Team",
    participants: [currentUser, mockUsers[5], mockUsers[4], mockUsers[1]],
    lastMessage: {
      id: "m6",
      senderId: "6",
      content: "Great job everyone! We hit our Q4 targets! 🎉",
      timestamp: new Date(Date.now() - 2 * 24 * 3600000),
      status: "read",
    },
    unreadCount: 5,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 90 * 24 * 3600000),
    updatedAt: new Date(Date.now() - 2 * 24 * 3600000),
  },
];

export const generateMockMessages = (conversationId: string): Message[] => {
  return [
    {
      id: "msg1",
      senderId: "1",
      content: "Hey! How's the project coming along?",
      timestamp: new Date(Date.now() - 2 * 3600000),
      status: "read",
    },
    {
      id: "msg2",
      senderId: "current",
      content: "Going well! We're about 80% done with the main features.",
      timestamp: new Date(Date.now() - 2 * 3600000 + 120000),
      status: "read",
    },
    {
      id: "msg3",
      senderId: "1",
      content: "That's great to hear! Do you have an updated timeline?",
      timestamp: new Date(Date.now() - 2 * 3600000 + 300000),
      status: "read",
    },
    {
      id: "msg4",
      senderId: "current",
      content: "Yes, I've prepared a detailed timeline. Let me share it with you.",
      timestamp: new Date(Date.now() - 1.5 * 3600000),
      status: "read",
    },
    {
      id: "msg5",
      senderId: "current",
      content: "Here's the project timeline document",
      timestamp: new Date(Date.now() - 1.5 * 3600000 + 60000),
      status: "read",
      attachments: [
        { id: "att1", type: "file", name: "Project_Timeline_v2.pdf", url: "#", size: "1.2 MB" },
      ],
    },
    {
      id: "msg6",
      senderId: "1",
      content: "Perfect! I'll review it and get back to you. Also, here are some reference images.",
      timestamp: new Date(Date.now() - 1 * 3600000),
      status: "read",
      attachments: [
        {
          id: "att2",
          type: "image",
          name: "ui_reference_1.png",
          url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
          preview: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
        },
        {
          id: "att3",
          type: "image",
          name: "ui_reference_2.png",
          url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
          preview: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
        },
      ],
    },
    {
      id: "msg7",
      senderId: "current",
      content: "These look amazing! I especially like the dashboard layout. We could incorporate that.",
      timestamp: new Date(Date.now() - 45 * 60000),
      status: "read",
    },
    {
      id: "msg8",
      senderId: "1",
      content: "Agreed! Let's schedule a call to discuss. How about tomorrow at 2 PM?",
      timestamp: new Date(Date.now() - 30 * 60000),
      status: "read",
    },
    {
      id: "msg9",
      senderId: "current",
      content: "Tomorrow at 2 PM works for me! I'll send a calendar invite.",
      timestamp: new Date(Date.now() - 15 * 60000),
      status: "read",
    },
    {
      id: "msg10",
      senderId: "1",
      content: "Sure, I'll send over the project files by EOD!",
      timestamp: new Date(Date.now() - 5 * 60000),
      status: "read",
    },
  ];
};