ALTER TYPE "QuoteStatus" ADD VALUE IF NOT EXISTS 'VIEWED';
ALTER TYPE "QuoteStatus" ADD VALUE IF NOT EXISTS 'SIGNED';

ALTER TABLE "Quote"
ADD COLUMN "isContract" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "contractVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "viewCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "firstViewedAt" TIMESTAMP(3),
ADD COLUMN "lastViewedAt" TIMESTAMP(3),
ADD COLUMN "signedAt" TIMESTAMP(3),
ADD COLUMN "signedBy" TEXT,
ADD COLUMN "signatureType" TEXT,
ADD COLUMN "signatureData" TEXT,
ADD COLUMN "signerIpAddress" TEXT,
ADD COLUMN "signerUserAgent" TEXT,
ADD COLUMN "contractSnapshot" JSONB,
ADD COLUMN "auditTrail" JSONB,
ADD COLUMN "signedPdfFileId" TEXT,
ADD COLUMN "rejectedAt" TIMESTAMP(3);
