import { Router } from 'express';
import { z } from 'zod';
import { loadEmployee } from '../../common/middleware/auth.middleware';
import { requirePermission } from '../../common/middleware/permission.middleware';
import { rateLimiter } from '../../common/middleware/rateLimiter.middleware';
import { validate } from '../../common/middleware/validate.middleware';
import { PERMISSIONS } from '../../common/constants/permissions';
import { websiteAnalyticsController } from './website-analytics.controller';

const idSchema = z.object({ params: z.object({ id: z.string().uuid() }) }).passthrough();
const runIdSchema = z.object({ params: z.object({ runId: z.string().uuid() }) }).passthrough();
const sessionIdSchema = z.object({ params: z.object({ sessionId: z.string().uuid() }) }).passthrough();
const tagIdSchema = z.object({ params: z.object({ id: z.string().uuid(), tagId: z.string().uuid() }) }).passthrough();
const bodySchema = z.object({ body: z.object({}).passthrough() }).passthrough();

export const websiteAnalyticsPublicRoutes = Router();

websiteAnalyticsPublicRoutes.get('/tracker.js', websiteAnalyticsController.tracker.bind(websiteAnalyticsController));
websiteAnalyticsPublicRoutes.get('/vendor/rrweb-record.js', websiteAnalyticsController.vendorRecorder.bind(websiteAnalyticsController));
websiteAnalyticsPublicRoutes.get('/shared-recordings/:shareToken', websiteAnalyticsController.getSharedRecording.bind(websiteAnalyticsController));
websiteAnalyticsPublicRoutes.get('/shared-recordings/:shareToken/chunks', websiteAnalyticsController.getSharedRecordingChunks.bind(websiteAnalyticsController));
websiteAnalyticsPublicRoutes.post('/session/start', rateLimiter({ windowMs: 60 * 1000, max: 600 }), validate(bodySchema), websiteAnalyticsController.startSession.bind(websiteAnalyticsController));
websiteAnalyticsPublicRoutes.post('/session/end', rateLimiter({ windowMs: 60 * 1000, max: 600 }), validate(bodySchema), websiteAnalyticsController.endSession.bind(websiteAnalyticsController));
websiteAnalyticsPublicRoutes.post('/collect', rateLimiter({ windowMs: 60 * 1000, max: 1200 }), validate(bodySchema), websiteAnalyticsController.collect.bind(websiteAnalyticsController));
websiteAnalyticsPublicRoutes.post('/recordings/start', rateLimiter({ windowMs: 60 * 1000, max: 300 }), validate(bodySchema), websiteAnalyticsController.startRecording.bind(websiteAnalyticsController));
websiteAnalyticsPublicRoutes.post('/recordings/chunk', rateLimiter({ windowMs: 60 * 1000, max: 900 }), validate(bodySchema), websiteAnalyticsController.uploadRecordingChunk.bind(websiteAnalyticsController));
websiteAnalyticsPublicRoutes.post('/recordings/end', rateLimiter({ windowMs: 60 * 1000, max: 300 }), validate(bodySchema), websiteAnalyticsController.endRecording.bind(websiteAnalyticsController));

const router = Router();

router.use(loadEmployee);

router.get('/sites', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listSites.bind(websiteAnalyticsController));
router.post('/sites', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(bodySchema), websiteAnalyticsController.createSite.bind(websiteAnalyticsController));
router.get('/sites/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getSite.bind(websiteAnalyticsController));
router.put('/sites/:id', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.updateSite.bind(websiteAnalyticsController));
router.delete('/sites/:id', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), websiteAnalyticsController.deactivateSite.bind(websiteAnalyticsController));
router.get('/sites/:id/snippet', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getSnippet.bind(websiteAnalyticsController));
router.get('/segments', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listSegments.bind(websiteAnalyticsController));
router.post('/segments', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(bodySchema), websiteAnalyticsController.createSegment.bind(websiteAnalyticsController));
router.get('/segments/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getSegment.bind(websiteAnalyticsController));
router.put('/segments/:id', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.updateSegment.bind(websiteAnalyticsController));
router.delete('/segments/:id', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), websiteAnalyticsController.deleteSegment.bind(websiteAnalyticsController));
router.get('/filter-options', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.getFilterOptions.bind(websiteAnalyticsController));
router.get('/funnels', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listFunnels.bind(websiteAnalyticsController));
router.post('/funnels', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(bodySchema), websiteAnalyticsController.createFunnel.bind(websiteAnalyticsController));
router.get('/funnels/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getFunnel.bind(websiteAnalyticsController));
router.put('/funnels/:id', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.updateFunnel.bind(websiteAnalyticsController));
router.delete('/funnels/:id', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), websiteAnalyticsController.deleteFunnel.bind(websiteAnalyticsController));
router.post('/funnels/:id/run', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.runFunnel.bind(websiteAnalyticsController));
router.get('/funnels/:id/runs', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.listFunnelRuns.bind(websiteAnalyticsController));
router.get('/funnel-runs/:runId', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(runIdSchema), websiteAnalyticsController.getFunnelRun.bind(websiteAnalyticsController));
router.get('/funnel-runs/:runId/sessions', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(runIdSchema), websiteAnalyticsController.listFunnelRunSessions.bind(websiteAnalyticsController));
router.post('/journeys/analyze', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(bodySchema), websiteAnalyticsController.analyzeJourneys.bind(websiteAnalyticsController));
router.get('/journeys/paths', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listJourneyPaths.bind(websiteAnalyticsController));
router.get('/journeys/aggregates', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listJourneyAggregates.bind(websiteAnalyticsController));
router.get('/journeys/paths/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getJourneyPath.bind(websiteAnalyticsController));
router.get('/journeys/sessions/:sessionId', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(sessionIdSchema), websiteAnalyticsController.getSessionJourney.bind(websiteAnalyticsController));
router.get('/ai/insights', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listAiInsights.bind(websiteAnalyticsController));
router.post('/ai/insights/generate', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(bodySchema), websiteAnalyticsController.generateAiInsight.bind(websiteAnalyticsController));
router.get('/ai/insights/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getAiInsight.bind(websiteAnalyticsController));
router.patch('/ai/insights/:id/status', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.updateAiInsightStatus.bind(websiteAnalyticsController));
router.post('/ai/sessions/:sessionId/summary', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(sessionIdSchema), websiteAnalyticsController.summarizeAiSession.bind(websiteAnalyticsController));
router.post('/ai/recordings/:recordingId/summary', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(z.object({ params: z.object({ recordingId: z.string().uuid() }) }).passthrough()), websiteAnalyticsController.summarizeAiRecording.bind(websiteAnalyticsController));
router.get('/ai/conversations', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listAiConversations.bind(websiteAnalyticsController));
router.post('/ai/conversations', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(bodySchema), websiteAnalyticsController.createAiConversation.bind(websiteAnalyticsController));
router.get('/ai/conversations/:id/messages', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.listAiMessages.bind(websiteAnalyticsController));
router.post('/ai/conversations/:id/messages', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.createAiMessage.bind(websiteAnalyticsController));
router.get('/sessions', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listSessions.bind(websiteAnalyticsController));
router.get('/sessions/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getSession.bind(websiteAnalyticsController));
router.get('/sessions/:id/tags', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.listSessionTags.bind(websiteAnalyticsController));
router.post('/sessions/:id/tags', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.createSessionTag.bind(websiteAnalyticsController));
router.delete('/sessions/:id/tags/:tagId', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(tagIdSchema), websiteAnalyticsController.deleteSessionTag.bind(websiteAnalyticsController));
router.get('/visitors/:id/identity', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getVisitorIdentity.bind(websiteAnalyticsController));
router.put('/visitors/:id/identity', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.updateVisitorIdentity.bind(websiteAnalyticsController));
router.get('/events', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listEvents.bind(websiteAnalyticsController));
router.get('/heatmaps', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listHeatmaps.bind(websiteAnalyticsController));
router.post('/heatmaps/snapshots', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(bodySchema), websiteAnalyticsController.createHeatmapSnapshot.bind(websiteAnalyticsController));
router.get('/heatmaps/snapshots/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getHeatmapSnapshot.bind(websiteAnalyticsController));
router.get('/heatmaps/snapshots/:id/points', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getHeatmapPoints.bind(websiteAnalyticsController));
router.delete('/heatmaps/snapshots/:id', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), websiteAnalyticsController.deleteHeatmapSnapshot.bind(websiteAnalyticsController));
router.get('/behavior/signals', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listBehaviorSignals.bind(websiteAnalyticsController));
router.get('/behavior/signals/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getBehaviorSignal.bind(websiteAnalyticsController));
router.get('/behavior/issues', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listBehaviorIssues.bind(websiteAnalyticsController));
router.get('/behavior/issues/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getBehaviorIssue.bind(websiteAnalyticsController));
router.patch('/behavior/issues/:id/status', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.updateBehaviorIssueStatus.bind(websiteAnalyticsController));
router.post('/behavior/sessions/:sessionId/analyze', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(sessionIdSchema), websiteAnalyticsController.analyzeSession.bind(websiteAnalyticsController));
router.get('/recordings', requirePermission(PERMISSIONS.ANALYTICS_VIEW), websiteAnalyticsController.listRecordings.bind(websiteAnalyticsController));
router.get('/recordings/:id', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getRecording.bind(websiteAnalyticsController));
router.get('/recordings/:id/chunks', requirePermission(PERMISSIONS.ANALYTICS_VIEW), validate(idSchema), websiteAnalyticsController.getRecordingChunks.bind(websiteAnalyticsController));
router.patch('/recordings/:id/favorite', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.setRecordingFavorite.bind(websiteAnalyticsController));
router.patch('/recordings/:id/labels', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), validate(bodySchema), websiteAnalyticsController.setRecordingLabels.bind(websiteAnalyticsController));
router.post('/recordings/:id/share', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), websiteAnalyticsController.enableRecordingShare.bind(websiteAnalyticsController));
router.delete('/recordings/:id/share', requirePermission(PERMISSIONS.ANALYTICS_EXPORT), validate(idSchema), websiteAnalyticsController.disableRecordingShare.bind(websiteAnalyticsController));

export default router;
